### ISSUE TITLE
disable btn error

### ISSUE THREAD

**Issue by Quacrom** [mikejacobson/bootstrap4-scrolling-tabs#2]
Hi friends

Thanks for your pluging.

When the **disablerrowsonfullycrolled** option is activated in TRUE, it correctly disables the first or last button according to the case (visually the scrtabs-disable class), even so, you can click on the causing that you can continue to progress even though There is content.

How can you prevent clicking on a disabled button?

Thanks

**Comment by mikejacobson** [comment]
The `disableScrollArrowsOnFullyScrolled` option, as you discovered, just adds CSS class `scrtabs-disable` and its associated styling to the appropriate arrow on full scroll. If you need extra functionality associated with that, you would need to add your own code that checks for that class.

If the scrolling element is fully scrolled, though, clicking the disabled button shouldn't have an effect, I wouldn't think, unless your implementation adds some additional functionality to those buttons.

**Comment by Quacrom** [comment]
Thanks for your prompt response Mike.

I explain my case, with the configuration activated:

`disableScrollArrowsOnFullyScrolled: true`

The scartabs-disable class is correctly enabled upon arrival at the end of the Tabs as indicated:

![imagen](https://user-images.githubusercontent.com/13321249/119926889-428bb480-bf46-11eb-8ab3-cdc77e74649c.png).


Despite being "disabled" I can continue to click and move forward:

![imagen](https://user-images.githubusercontent.com/13321249/119926918-57684800-bf46-11eb-812d-06603b8af1ee.png)


Try creating a function in this case:

`$('div.scrtabs-disable').click(function(){return false;});`

But I can not get stopping or disabling the Click function without having to intervene or spy on the source code of your script.

Is there any way to stop action click when the scartabs-disable class is activated?

Thanks

**Comment by mikejacobson** [comment]
The only way I could think of to essentially intercept the plugin's click handlers is to use the [Custom Scroll Arrow Content](https://github.com/mikejacobson/bootstrap4-scrolling-tabs#custom-scroll-arrow-content) option.

That option allows you to define the HTML for the scroll arrows, which would allow you to define inline event handlers on the arrows. Because those inline handlers would execute before the plugin's handlers, calling `event.stopImmediatePropagation()` would prevent the plugin's handlers from executing.

[Here's a CodePen](https://codepen.io/mikejacobson/pen/JjWOoRM?editors=0011) showing this approach.

So your plugin initialization would look something like this, with `leftArrowContent` and `rightArrowContent` options defined:
```js
$('.nav-tabs').scrollingTabs({
  leftArrowContent: `
    <div class="scrtabs-tab-scroll-arrow scrtabs-tab-scroll-arrow-left"
      onmousedown="suppressEventIfDisabled(event)"
      onclick="suppressEventIfDisabled(event)">
      <span></span>
    </div>
  `,
  rightArrowContent: `
    <div class="scrtabs-tab-scroll-arrow scrtabs-tab-scroll-arrow-right"
      onmousedown="suppressEventIfDisabled(event)"
      onclick="suppressEventIfDisabled(event)">
      <span></span>
    </div>
  `,
  disableScrollArrowsOnFullyScrolled: true
})
```
The arrows' HTML just matches the plugin's default HTML except for the inline event handlers. Note that you need both `onmousedown` and `onclick` handlers because the plugin uses both.

Your event handler function would need to be defined somewhere accessibe to the plugin code. In my CodePen I just put it on the `window` object for simplicity, but of course that's not ideal:
```js
window.suppressEventIfDisabled = function(e) {
  if (e.currentTarget.classList.contains('scrtabs-disable')) {
    e.stopImmediatePropagation();
  }
}
```

**Comment by Quacrom** [comment]
Thanks, Mike

For me it works. Ideally, it should be by default for the disabled button not being able to continue with more actions.

![imagen](https://user-images.githubusercontent.com/13321249/120142975-48cf9a00-c1ad-11eb-8079-3473d83a4aa0.png)

Thank you very much for the help. Great job!

**Comment by mikejacobson** [comment]
Great! Glad it's working for you.

I could update the plugin to functionally disable the buttons when fully scrolled but I guess I don't understand how you can get into a state where the button is visually disabled due to the scrolling container being fully scrolled, but then it can be scrolled even further. If there's still more scrolling container available, the button shouldn't visually disable in the first place, I wouldn't think.
